BASE_URL="https://tobeto.com/giris"
IFRAME_ID="exw-launcher-frame"
LAUNCHER="launcher"
IFRAME_2="exw-conversation-frame"
ADGIR='/html/body/div/div/div/div[2]/div[2]/div[2]/div[2]/input'
ADGIR_TEXT="İrem balci"
GONDER_BUTTON="//*[@id='surveyForm']//*[@id='surveyBtn']"
IFRAME_MESSAGE_BOX="iframe[class='exw-conversation-container-frame']"
KUCULT_ICON="svg[class='exw-minimize-button header-button']"
KUCULT_ICON_SELECTOR="svg[class='exw-minimize-button header-button']"
BUTTON_ID="button[id='launcher']"
CHAT_BUTTON="//*[name()='svg' and @class='exw-end-session-button header-button']"
CHATBOX="h4[class='exw-title exw-with-avatar']"
EVET="//*[@id='exw-conversation-frame-body']/div/div/div/div[1]/div/div[3]/div/button[1]"
CEVAP="//*[@id='surveyTextArea']"
CEVAP_1="Bir seçenek seçiniz"
CEVAP_2="Bitirmel istiyorum"
ARGUMENT="arguments[0].click();"
MESSAGE="//*[@id='exw-messages']/div[2]/div/div/div/h3"
MESSAGE_INPUT="Geri bildiriminiz için teşekkürler!"
